services:
  backend:
    build:
      context: src/backend
    container_name: medchat-backend
    image: medchat-backend:latest
    volumes:
      - ./corpus:/app/corpus
      - ./logs/backend:/app/logs
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - model

  frontend:
    build:
      context: src/frontend
    container_name: medchat-frontend
    image: medchat-frontend:latest
    volumes:
      - ./logs/frontend:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - backend

  model:
    build:
      context: src/model
    container_name: medchat-model
    image: medchat-model:latest
    volumes:
      - ./logs/model:/app/logs
      - ./weights:/app/weights
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
          memory: 8G

  db:
    image: pgvector/pgvector:pg17
    container_name: medchat-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./databases/pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/medchat/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080