services:
  backend:
    build:
      context: src/backend
    image: chatbot-backend:latest
    volumes:
      - ./sources:/app/sources
      - ./logs:/app/logs
      - ./database:/app/database
    ports:
      - "5050:5050"
  frontend:
    build:
      context: src/frontend
    image: chatbot-frontend:latest
    volumes:
      - ./logs:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - backend

  model:
    build:
      context: src/model
    image: model-server:latest
    volumes:
      - ./logs:/app/logs
      - ./weights:/app/weights
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]