services:
  backend:
    build:
      context: src/backend
    container_name: medchat-backend
    image: medchat-backend:latest
    volumes:
      - ./sources:/app/sources
      - ./logs/backend:/app/logs
      - ./models:/app/models
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
          memory: 8G

  frontend:
    build:
      context: src/frontend
    container_name: medchat-frontend
    image: medchat-frontend:latest
    volumes:
      - ./logs/frontend:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: pgvector/pgvector:pg17
    container_name: medchat-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./databases/pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/medchat/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  blob-server:
    image: python:3.11-slim
    container_name: blob-server
    working_dir: /srv
    volumes:
      - ./sources:/srv:ro
    ports:
      - "9090:9090"
    command: python -m http.server 9090