
INFERENCE_MODEL="/app/models/BioMistral-7B-DARE-AWQ-QGS128-W4-GEMM"
DO_SAMPLE=false
MAX_NEW_TOKENS=1024

QUERY_EMBEDDING_MODEL="/app/models/MedCPT-Query-Encoder"
ARTICLE_EMBEDDING_MODEL="/app/models/MedCPT-Article-Encoder"
CROSS_ENCODER_MODEL="/app/models/MedCPT-Cross-Encoder"

DEVICE_MAP="cuda"